---
- hosts: all
  become: true

  tasks:
    - name: Install Alerta Heartbeat Service
      include_role:
        name: veloslab.alerta.heartbeat
      vars:
        alerta_heartbeat_origin: "{{ ansible_hostname }}"
