---
- hosts: all
  become: true
  vars:
    alerta_heartbeat_api_key: "{{ lookup('hashi_vault', 'secret=secret/alerta/api/heartbeat:key') }}"
    alerta_heartbeat_origin: "{{ ansible_hostname }}"

  tasks:
    - name: Testing
      debug:
        msg: "{{ alerta_heartbeat_api_key }}"
    - name: Testing 1
      debug:
        msg: "{{ alerta_heartbeat_origin }}"
    - name: Testing
      debug:
        msg: "{{ ansible_hostname }}"
