---
- hosts: all
  become: true
  vars:
    alerta_heartbeat_origin: "{{ ansible_hostname }}"

  tasks:
    - name: Testing
      debug:
        msg: "{{ alerta_heartbeat_api_key }}"
    - name: Testing 1
      debug:
        msg: "{{ alerta_heartbeat_origin }}"
