---
- hosts: all
  become: true
  roles:
    - veloslab.base.packages
  vars:
    python_version: '3.10'
    prefect_cloud: "{{ lookup('hashi_vault', 'secret=secret/data/prefect/cloud')}}"
    prefect_vault: "{{ lookup('hashi_vault', 'secret=secret/data/prefect/approle')}}"
    prefect_truenas: "{{ lookup('hashi_vault', 'secret=secret/data/truenas/ssh/prefect')}}"

  tasks:
    - name: Git checkout veloslab/prefect
      ansible.builtin.git:
        repo: 'https://github.com/veloslab/prefect.git'
        dest: /veloslab/prefect/lib/

    - name: Install Python
      include_role:
        name: veloslab.base.python

    - name: Create prefect venv
      ansible.builtin.pip:
        requirements: /veloslab/prefect/lib/requirements.txt
        virtualenv: '/veloslab/python/prefect{{ python_version }}'
        virtualenv_command: 'python{{ python_version }} -m venv'

    - name: Create a symbolic link
      ansible.builtin.file:
        src: '/veloslab/python/prefect{{ python_version }}'
        dest: /veloslab/python/prefect
        owner: root
        group: root
        state: link
        mode: 0755

    - name: Create directory for Chromium
      ansible.builtin.file:
        dest: 'veloslab/prefect/playwright'
        owner: root
        group: root
        state: directory
        mode: 0755

    - name: Install Chromium for playwright
      ansible.builtin.command:
        cmd: /veloslab/python/prefect/bin/playwright install chromium
      environment:
        PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright

          #    - name: Install Chrome for playwright
          #ansible.builtin.command:
          #cmd: /veloslab/python/prefect/bin/playwright install chrome --force
          #environment:
          #PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright

    - name: Create pth file for venv
      ansible.builtin.copy:
        dest: '/veloslab/python/prefect/lib/python{{ python_version }}/site-packages/prefect.pth'
        owner: root
        group: root
        mode: 0644
        content: '/veloslab/prefect/lib/'

    - name: Create prefect config directory
      ansible.builtin.file:
        path: /home/vls_prefect
        owner: vls_prefect
        group: vls_prefect
        state: directory
        mode: 0775

    - name: Create prefect ssh dir
      ansible.builtin.file:
        path: /home/vls_prefect/.ssh/
        owner: vls_prefect
        group: vls_prefect
        state: directory
        mode: 0775

    - name: Create prefect truenas key
      ansible.builtin.copy:
        dest: /home/vls_prefect/.ssh/id_ed25519_truenas
        owner: vls_prefect
        group: vls_prefect
        mode: 0600
        content: "{{ prefect_truenas['private_key'] }}"

    - name: Deploy Prefect Agent
      include_role:
        name: veloslab.prefect.agent
      vars:
        prefect_venv: /veloslab/python/prefect
        prefect_work_pool: veloslab-remote
        prefect_work_queue: default
        prefect_user: vls_prefect
        prefect_api_key: "{{ prefect_cloud['key'] }}"
        prefect_workspace: "{{ prefect_cloud['workspace'] }}"
        prefect_env:
          VAULT_ADDR: https://vault.veloslab.net
          VAULT_ROLE_ID: "{{ prefect_vault['role'] }}"
          VAULT_SECRET_ID: "{{ prefect_vault['secret'] }}"
          PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright
      when: "'prefect' in ansible_hostname"

    - name: Create cron to restart agent every 1 hours
      ansible.builtin.cron:
        name: "prefect agent restart"
        minute: "11"
        job: "/usr/bin/supervisorctl restart prefect-veloslab"
