---
- hosts: all
  become: true
  vars:
    prefect_cloud: "{{ lookup('hashi_vault', 'secret=secret/data/prefect/cloud')}}"
    prefect_vault: "{{ lookup('hashi_vault', 'secret=secret/data/prefect/approle')}}"
    python_version: 3.11

  tasks:
    - name: Git checkout veloslab/prefect
      ansible.builtin.git:
        repo: 'https://github.com/veloslab/prefect.git'
        dest: /veloslab/prefect/lib/

    - name: Create Python Environment
      include_role:
        name: veloslab.base.python_venv
      vars:
        python_venv_name: prefect
        python_venv_version: "{{python_version}}"
        python_venv_requirements:  /veloslab/prefect/lib/requirements.txt

    - name: Create directory for Chromium
      ansible.builtin.file:
        dest: '/veloslab/prefect/playwright'
        owner: root
        group: root
        state: directory
        mode: 0755

    - name: Install Chromium for playwright
      ansible.builtin.command:
        cmd: /veloslab/python/prefect/bin/playwright install chromium
      environment:
        PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright

          #    - name: Install Chrome for playwright
          #ansible.builtin.command:
          #cmd: /veloslab/python/prefect/bin/playwright install chrome --force
          #environment:
          #PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright

    - name: Create pth file for venv
      ansible.builtin.copy:
        dest: '/veloslab/python/prefect/lib/python{{ python_version }}/site-packages/prefect.pth'
        owner: root
        group: root
        mode: 0644
        content: '/veloslab/prefect/lib/'

    - name: Create prefect config directory
      ansible.builtin.file:
        path: /home/vls_prefect
        owner: vls_prefect
        group: vls_prefect
        state: directory
        mode: 0775

    - name: Create prefect ssh dir
      ansible.builtin.file:
        path: /home/vls_prefect/.ssh/
        owner: vls_prefect
        group: vls_prefect
        state: directory
        mode: 0775

    - name: Deploy Prefect Agent
      include_role:
        name: veloslab.prefect.agent
      vars:
        prefect_venv: /veloslab/python/prefect
        prefect_work_pool: veloslab-pool
        prefect_work_queue: default
        prefect_user: vls_prefect
        prefect_api_key: "{{ prefect_cloud['key'] }}"
        prefect_workspace: "{{ prefect_cloud['workspace'] }}"
        prefect_env:
          VAULT_ADDR: https://vault.veloslab.net
          VAULT_ROLE_ID: "{{ prefect_vault['role'] }}"
          VAULT_SECRET_ID: "{{ prefect_vault['secret'] }}"
          PLAYWRIGHT_BROWSERS_PATH: /veloslab/prefect/playwright
      when: "'prefect' in ansible_hostname"

    - name: Create cron to restart agent every hour
      ansible.builtin.cron:
        name: "prefect agent restart"
        minute: "11"
        job: "/usr/bin/supervisorctl restart prefect-veloslab"
