---
- hosts: all
  become: true
  vars:
    python_version: '3.10'

  tasks:
    - name: Git checkout veloslab/prefect
      ansible.builtin.git:
        repo: 'https://github.com/veloslab/prefect.git'
        dest: /veloslab/prefect/lib/

    - name: Update prefect venv
      ansible.builtin.pip:
        requirements: /veloslab/prefect/lib/requirements.txt
        virtualenv: '/veloslab/python/prefect{{ python_version }}'
        virtualenv_command: 'python{{ python_version }} -m venv'
